export const paths = {
  login: '/login',
  register: '/register',
  pending: '/pending',
  home: '/',
  dashboard: '/dashboard',
  student: (id: string) => `/student/${id}`,
  speaking: '/speaking',
  reading: '/reading',
  readingPractice: '/reading/practice',
  readingPracticeAdmin: '/reading/practice/admin',
  listening: '/listening',
  writing: '/writing',
  analytics: '/analytics',
  progress: '/progress',
  social: '/social',
  settings: '/settings',
  attendance: '/attendance',
  assignment: (id: string) => `/assignments/${id}`,
  teacher: '/teacher',
  approvals: '/approvals',
  notifications: '/notifications',
};
