export const paths = {
  login: '/login',
  register: '/register',
  pending: '/pending',
  home: '/',
  dashboard: '/dashboard',
  student: (id: string) => `/student/${id}`,
  speaking: '/speaking',
  reading: '/reading',
  readingPractice: '/reading/practice',
  readingPracticeCheck: '/reading/practice/check',
  readingPracticeIntro: '/reading/practice/intro',
  readingPracticeAdmin: '/reading/practice/admin',
  readingPracticeAdminResults: '/reading/practice/admin/results',
  readingPracticeAdminReport: (sessionId: string, studentId: string) =>
    `/reading/practice/admin/report/${sessionId}?studentId=${encodeURIComponent(studentId)}`,
  readingPracticeReport: (sessionId: string) => `/reading/practice/report/${sessionId}`,
  listening: '/listening',
  listeningPractice: '/listening/practice',
  listeningPracticeAdmin: '/listening/practice/admin',
  writing: '/writing',
  writingPractice: '/writing/practice',
  writingPracticeAdmin: '/writing/practice/admin',
  analytics: '/analytics',
  progress: '/progress',
  social: '/social',
  settings: '/settings',
  attendance: '/attendance',
  assignment: (id: string) => `/assignments/${id}`,
  teacher: '/teacher',
  approvals: '/approvals',
  notifications: '/notifications',
};
